FROM debian:11

RUN apt update && apt upgrade -y && apt install wget -y
RUN apt install vim -y
RUN apt-get install -y php7.3 php-mysql php-fpm mariadb-client
RUN wget https://wordpress.org/latest.tar.gz -P /var/www
RUN cd /var/www && tar -xzf latest.tar.gz && rm latest.tar.gz
# RUN	chown -R root:root /var/www/wordpress
COPY conf/www.conf /etc/php/7.4/fpm/pool.d
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
COPY conf/scripts.sh /
RUN chmod +x /scripts.sh
RUN mkdir -p /run/php
COPY conf/wp-config.php /var/www/wordpress

CMD ["sh", "scripts.sh"]
