FROM debian:11

RUN apt update && apt upgrade -y && apt install nginx -y
RUN mkdir -p /etc/nginx/ssl
RUN apt install openssl -y
RUN apt install vim -y 
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt \
-keyout /etc/nginx/ssl/inception.key -subj "/C=MA/ST=RABAT/L=RABAT/O=INCEPTION/OU=INCEPTION/CN=138.68.98.21/UID=138.68.98.21"
RUN mkdir -p /var/run/nginx
RUN mkdir -p /var/www/wordpress
COPY conf/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
